// Code generated by sqlc. DO NOT EDIT.
// source: message.sql

package DB

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO msg
( msg,msg_id, event,fk_user,created_at)
VALUES ($1,$2,$3,$4,$5) RETURNING id
`

type InsertMessageParams struct {
	Msg       string
	MsgID     string
	Event     string
	FkUser    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.Msg,
		arg.MsgID,
		arg.Event,
		arg.FkUser,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
